# Generated by Django 4.1.1 on 2022-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_basket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Busket',
        ),
    ]
